version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Map host port 3000 to container port 3000
    environment:
      - NODE_ENV=development
      - PORT=5000
    command: npm run dev # Start the development server
    image: url-shortener-server
    networks:
      - app-network

  mongodb:
    image: mongo:4.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    image: url-shortener-client
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
